apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app1-jd
- app2-md
labels:
- pairs:
    project: dynatrace-demo
    managed-by: kustomize
    includeSelectors: true
    includeTemplates: true