apiVersion: v1
kind: Namespace
metadata:
  name: app1-jd-ns1
  labels:
    app: app1-jd
    environment: demo
    namespace-id: ns1
---
apiVersion: v1
kind: Namespace
metadata:
  name: app1-jd-ns2
  labels:
    app: app1-jd
    environment: demo
    namespace-id: ns2
---
apiVersion: v1
kind: Namespace
metadata:
  name: app2-md-ns1
  labels:
    app: app2-md
    environment: demo
    namespace-id: ns1
---
apiVersion: v1
kind: Namespace
metadata:
  name: app2-md-ns2
  labels:
    app: app2-md
    environment: demo
    namespace-id: ns2