apiVersion: v1
kind: Service
metadata:
  name: app2-md
  namespace: app2-md-ns1
  labels:
    app: app2-md
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: app2-md
---
apiVersion: v1
kind: Service
metadata:
  name: app2-md
  namespace: app2-md-ns2
  labels:
    app: app2-md
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: app2-md